Repository atlp-rwanda/e-comm-team-techtitans-bn, pull requests merged in 2023-04, with the labels that each got.

#29 Ft reset password
  .env.example
  docs/forgot.password.doc.yaml
  docs/user.logout.yaml
  lib/controllers/user.controller.js
  lib/database/models/index.js
  lib/routes/user.routes.js
  lib/utils/resetPasswordEmail.js
  src/controllers/user.controller.js
  src/database/models/index.js
  src/routes/user.routes.js
  src/utils/resetPasswordEmail.js
Labels: Ready to Merge

#33 resolve conflict
  lib/controllers/user.controller.js
  lib/database/models/user.js
  lib/routes/user.routes.js
  package-lock.json
  src/controllers/user.controller.js
Labels: Ready to Merge

#30 #184752227 fix the current file_structure_and_usage in the project
  docs/1sendVerificationEmail.docs.yaml
  docs/2login.docs.yaml
  docs/3logout.docs.yaml
  docs/example.doc.yaml
  lib/controllers/product/product.controller.js
  lib/controllers/user/findAllUsers.controller.js
  lib/controllers/user/forgotPassword.controller.js
  lib/controllers/user/login.controller.js
  lib/controllers/user/logout.controller.js
  lib/controllers/user/profile.controller.js
  lib/controllers/user/signup.controller.js
  lib/database/config/config.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/models/index.js
  lib/database/models/user.js
  lib/database/seeders/20230322155518-techtitans.js
  lib/routes/index.js
  lib/routes/user.routes.js
  package.json
  src/controllers/index.js
  src/controllers/product/product.controller.js
  src/controllers/profile.controller.js
  src/controllers/user.controller.js
  src/controllers/user.logout.controller.js
  src/controllers/user/findAllUsers.controller.js
  src/controllers/user/forgotPassword.controller.js
  src/controllers/user/login.controller.js
  src/controllers/user/logout.controller.js
  src/controllers/user/profile.controller.js
  src/controllers/user/signup.controller.js
  src/database/config/config.js
  src/database/migrations/20230322155803-create-user.js
  src/database/migrations/20230327133121-create-profile.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20230322155518-techtitans.js
  src/routes/index.js
  src/routes/logout.routes.js
  src/routes/user.routes.js
  tests/mocks/user.mock.js
  tests/preTest.js
  tests/user/logout.test.js
  tests/user/signup_login.test.js
Labels: Ready to Merge

#35 #184752251 Update password
  docs/update.password.yaml
  lib/controllers/user.edit.password.js
  lib/controllers/user/forgotPassword.controller.js
  lib/controllers/user/user.edit.password.js
  lib/routes/user.routes.js
  src/controllers/user/user.edit.password.js
  src/routes/user.routes.js
  tests/preTest.js
  tests/user/update.password.test.js
Labels: Ready to Merge

#46 #[184779971] pull request template
  .github/workflows/pull_request_template.md
Labels: Need Peer Review, Ready to Merge

#37 #184752243 As a user, I can login-in/sign-up to the app via Google.
  .env.example
  docs/google.oauth.docs.yaml
  lib/app.js
  lib/database/config/config.js
  lib/middleware/auth/passport.auth.js
  lib/routes/index.js
  lib/routes/oauth.routes.js
  package-lock.json
  package.json
  src/app.js
  src/middleware/auth/passport.auth.js
  src/routes/index.js
  src/routes/oauth.routes.js
  views/pages/index.ejs
Labels: Need Peer Review, Changes Fixed

#51 #184752253 feature(product_features): a seller should be able to view and manage their product collection
  docs/product.docs.yaml
  lib/app.js
  lib/controllers/product/product.controller.js
  lib/controllers/user/login.controller.js
  lib/database/config/config.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/migrations/20230323050333-create-category.js
  lib/database/migrations/20230323050359-create-product.js
  lib/database/models/category.js
  lib/database/models/product.js
  lib/database/models/user.js
  lib/middleware/auth/auth.middleware.js
  lib/middleware/validation/product.schema.middleware.js
  lib/routes/index.js
  lib/routes/product.routes.js
  package-lock.json
  package.json
  src/app.js
  src/controllers/product/product.controller.js
  src/controllers/user/login.controller.js
  src/database/config/config.js
  src/database/migrations/20230322155803-create-user.js
  src/database/migrations/20230323050333-create-category.js
  src/database/migrations/20230323050359-create-product.js
  src/database/models/category.js
  src/database/models/product.js
  src/database/models/user.js
  src/middleware/auth/auth.middleware.js
  src/middleware/validation/product.schema.middleware.js
  src/routes/index.js
  src/routes/product.routes.js
Labels: Ready to Merge

#50 #184752252 feature(add product) A seller should be able to Create a product
  docs/index.js
  docs/product.docs.yaml
  lib/controllers/product/product.controller.js
  lib/controllers/user.edit.password.js
  lib/controllers/user/login.controller.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/migrations/20230323050333-create-category.js
  lib/database/migrations/20230323050359-create-product.js
  lib/database/migrations/20230323050447-create-category.js
  lib/database/models/user.js
  lib/middleware/auth/auth.middleware.js
  src/controllers/product/product.controller.js
  src/controllers/user/login.controller.js
  src/database/migrations/20230322155803-create-user.js
  src/database/migrations/20230323050333-create-category.js
  src/database/migrations/20230323050359-create-product.js
  src/database/models/user.js
  src/middleware/auth/auth.middleware.js
  tests/mocks/product.mock.js
  tests/product/product.test.js
Labels: Ready to Merge

#32 #[184752244] [Authorization: protected routes (all) should only be accessed by authenticated users]
  lib/controllers/user/forgotPassword.controller.js
  lib/controllers/user/signup.controller.js
  lib/database/config/config.js
  lib/database/models/user.js
  lib/middleware/auth/auth.middleware.js
  lib/middleware/auth/passport.auth.js
  lib/routes/product.routes.js
  lib/routes/user.routes.js
  src/controllers/user/forgotPassword.controller.js
  src/controllers/user/signup.controller.js
  src/database/config/config.js
  src/database/models/user.js
  src/middleware/auth/auth.middleware.js
  src/middleware/auth/passport.auth.js
  src/routes/product.routes.js
  src/routes/user.routes.js
Labels: Ready to Merge

#52 #184752252 fix(add product): transform specific product inputs to lowercase
  lib/controllers/product/product.controller.js
  lib/database/config/config.js
  lib/database/migrations/20230323050359-create-product.js
  lib/database/models/product.js
  lib/database/seeders/20230322155518-techtitans.js
  lib/routes/product.routes.js
  src/controllers/product/product.controller.js
  src/database/migrations/20230323050359-create-product.js
  src/database/models/product.js
  src/database/seeders/20230322155518-techtitans.js
  src/routes/product.routes.js
Labels: Ready to Merge

#53 #184752233 fix circleci test
  .circleci/config.yml
  lib/controllers/user/findAllUsers.controller.js
  lib/controllers/user/signup.controller.js
  lib/database/config/config.js
  lib/routes/product.routes.js
  lib/utils/send.email.js
  package.json
  src/controllers/user/findAllUsers.controller.js
  src/controllers/user/signup.controller.js
  src/database/config/config.js
  src/utils/send.email.js
  tests/mocks/user.mock.js
  tests/preTest.js
  tests/product/product.test.js
  tests/user/signup_login.test.js
  tests/user/update.password.test.js
Labels: Ready to Merge

#55 #184752273 User should be prompted to change their passwords
  lib/app.js
  lib/controllers/user/forgotPassword.controller.js
  lib/controllers/user/password.reminder.js
  lib/controllers/user/user.edit.password.js
  lib/database/config/config.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/models/user.js
  lib/middleware/auth/check.password.update.js
  lib/routes/user.routes.js
  lib/utils/send.email.js
  package-lock.json
  package.json
  src/app.js
  src/controllers/user/forgotPassword.controller.js
  src/controllers/user/password.reminder.js
  src/controllers/user/user.edit.password.js
  src/database/migrations/20230322155803-create-user.js
  src/database/models/user.js
  src/middleware/auth/check.password.update.js
  src/routes/user.routes.js
  src/utils/send.email.js
Labels: Ready to Merge

#40 #184752249 : ft-disable and enable account
  docs/enableDisableAccount.doc.yaml
  lib/controllers/user/disableEnableUsers.controller.js
  lib/controllers/user/login.controller.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/models/user.js
  lib/routes/user.routes.js
  lib/utils/send.email.js
  src/controllers/user/disableEnableUsers.controller.js
  src/controllers/user/login.controller.js
  src/database/migrations/20230322155803-create-user.js
  src/database/models/user.js
  src/routes/user.routes.js
  src/utils/send.email.js
  tests/user/enableDisableAccount.test.js
  tests/user/signup_login.test.js
Labels: Need Peer Review, Ready to Merge

#64 #184752257:ft-user-list-all-items
  docs/enableDisableAccount.doc.yaml
  lib/controllers/user/disableEnableUsers.controller.js
  lib/controllers/user/login.controller.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/models/user.js
  lib/routes/user.routes.js
  lib/utils/send.email.js
  src/controllers/user/disableEnableUsers.controller.js
  src/controllers/user/login.controller.js
  src/database/migrations/20230322155803-create-user.js
  src/database/models/user.js
  src/routes/user.routes.js
  src/utils/send.email.js
  tests/user/enableDisableAccount.test.js
  tests/user/signup_login.test.js
Labels: In Progress

#57 #184752269 ft(buyer-make-payments):Buyer should be able to make a payment using Stripe API
  docs/payment.docs.yaml
  lib/controllers/product/handle.payment.js
  lib/controllers/user/login.controller.js
  lib/controllers/user/pay.controller.js
  lib/database/seeders/20230322155518-techtitans.js
  lib/middleware/auth/auth.middleware.js
  lib/routes/index.js
  lib/routes/pay.routes.js
  package-lock.json
  package.json
  src/controllers/user/login.controller.js
  src/controllers/user/pay.controller.js
  src/database/config/config.js
  src/database/seeders/20230322155518-techtitans.js
  src/middleware/auth/auth.middleware.js
  src/routes/index.js
  src/routes/pay.routes.js
  src/routes/roles.routes.js
  tests/user/logout.test.js
  tests/user/signup_login.test.js
Labels: Ready to Merge

#43 #184752262 User/buyer should be able to add items to their cart
  lib/controllers/cart/addToCart.controller.js
  lib/controllers/cart/clearCart.controller.js
  lib/controllers/user/2fauthentication.controller.js
  lib/controllers/user/profile.controller.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/migrations/20230323050130-create-cart.js
  lib/database/migrations/20230323050359-create-product.js
  lib/database/models/cart.js
  lib/database/models/index.js
  lib/database/models/user.js
  lib/routes/index.js
  lib/routes/user.routes.js
  package-lock.json
  package.json
  src/controllers/cart/addToCart.controller.js
  src/controllers/cart/clearcart.controller.js
  src/controllers/user/2fauthentication.controller.js
  src/controllers/user/profile.controller.js
  src/database/migrations/20230322155803-create-user.js
  src/database/migrations/20230323050130-create-cart.js
  src/database/migrations/20230323050359-create-product.js
  src/database/models/cart.js
  src/database/models/index.js
  src/database/models/user.js
  src/routes/cart.routes.js
  src/routes/index.js
  src/routes/user.routes.js
  src/utils/send.email.js
  tests/preTest.js
  tests/user/enableDisableAccount.test.js
  tests/user/logout.test.js
  tests/user/signup_login.test.js
Labels: Ready to Merge

#60 #[184752266]:A user should be able to search a product
  docs/product.search.yaml
  lib/controllers/product/search.controller.js
  lib/routes/product.routes.js
  src/controllers/product/search.controller.js
  src/routes/product.routes.js
Labels: Ready to Merge

#62 #184752258 feature(update product) A seller should be able to update a product from their collection
  lib/controllers/product/getOneProduct.controller.js
  lib/controllers/product/handle.payment.js
  lib/controllers/product/product.controller.js
  lib/controllers/user/disableEnableUsers.controller.js
  lib/controllers/user/signup.controller.js
  lib/middleware/auth/passport.auth.js
  lib/routes/product.routes.js
  lib/routes/roles.routes.js
  lib/routes/user.routes.js
  src/controllers/product/product.controller.js
  src/controllers/user/disableEnableUsers.controller.js
  src/controllers/user/signup.controller.js
  src/routes/product.routes.js
  src/routes/user.routes.js
  tests/mocks/product.mock.js
  tests/user/signup_login.test.js
Labels: Ready to Merge

#68 #184752259 feature(buyer-wishlist): buyer wish list
  lib/controllers/product/wishlist.controller.js
  lib/database/migrations/20230419211749-create-wishlist.js
  lib/database/models/wishlist.js
  lib/routes/product.routes.js
  src/controllers/product/wishlist.controller.js
  src/database/migrations/20230419211749-create-wishlist.js
  src/database/models/wishlist.js
  src/routes/product.routes.js
Labels: Ready to Merge

#45 #184752265:feature(clear cart):Buyer should be able to clear their cart
  lib/controllers/cart/clearcart.controller.js
  lib/controllers/user/clearcart.controller.js
  lib/routes/cart.routes.js
  src/controllers/cart/clearcart.controller.js
  src/routes/cart.routes.js
Labels: Ready to Merge

#69 #184752263 Buyer should be able to update their cart
  docs/cart.yaml
  docs/profile.yaml
  lib/controllers/cart/addToCart.controller.js
  lib/controllers/cart/cartFunction.js
  lib/controllers/cart/clearcart.controller.js
  lib/controllers/cart/viewCart.js
  lib/controllers/product/checkout.controller.js
  lib/controllers/user/pay.controller.js
  lib/controllers/user/profile.controller.js
  lib/database/migrations/20230323050333-create-category.js
  lib/database/models/user.js
  lib/middleware/auth/passport.auth.js
  lib/routes/cart.routes.js
  lib/routes/product.routes.js
  lib/routes/user.routes.js
  src/controllers/cart/addToCart.controller.js
  src/controllers/cart/cartFunction.js
  src/controllers/cart/clearcart.controller.js
  src/controllers/cart/viewCart.js
  src/controllers/user/profile.controller.js
  src/database/migrations/20230323050333-create-category.js
  src/database/models/user.js
  src/routes/cart.routes.js
  src/routes/product.routes.js
  src/routes/user.routes.js
  tests/user/signup_login.test.js
Labels: Ready to Merge

#67 #184752272 The products should stop listing if the expiry date has passed
  lib/app.js
  lib/controllers/product/product.expiration.js
  lib/utils/send.email.js
  src/app.js
  src/controllers/product/product.expiration.js
  src/utils/send.email.js
Labels: Need Peer Review

#66 #184752257:ft-user-list-all-items
  docs/product.docs.yaml
  lib/controllers/product/product.controller.js
  lib/routes/product.routes.js
  src/controllers/product/product.controller.js
  src/routes/product.routes.js
  tests/product/product.test.js
Labels: Ready to Merge

#78 #184797979: implement pagination support for all get endpoints
  lib/controllers/product/product.controller.js
  lib/controllers/product/wishlist.controller.js
  lib/controllers/user/findAllUsers.controller.js
  lib/controllers/user/password.reminder.js
  lib/routes/user.routes.js
  src/controllers/product/product.controller.js
  src/controllers/product/wishlist.controller.js
  src/controllers/user/findAllUsers.controller.js
  src/controllers/user/password.reminder.js
  src/routes/user.routes.js
Labels: Ready to Merge

#75 ft(crud-order): a buyer ,I should be able to to crud an order
  docs/order.docs.yaml
  docs/product.docs.yaml
  lib/controllers/cart/addToCart.controller.js
  lib/controllers/cart/cartFunction.js
  lib/controllers/cart/viewCart.js
  lib/controllers/notification/notifications.controller.js
  lib/controllers/order/order.controller.js
  lib/controllers/order/updateOrderStatus.controller.js
  lib/controllers/user/clearcart.controller.js
  lib/database/migrations/20230323050734-create-order.js
  lib/database/migrations/20230425130623-create-order-product.js
  lib/database/models/cart.js
  lib/database/models/index.js
  lib/database/models/order.js
  lib/database/models/orderproduct.js
  lib/database/models/product.js
  lib/database/models/user.js
  lib/database/seeders/20230415092102-create-order.js
  lib/middleware/auth/auth.middleware.js
  lib/routes/order.routes.js
  package-lock.json
  package.json
  src/controllers/cart/addToCart.controller.js
  src/controllers/cart/cartFunction.js
  src/controllers/cart/viewCart.js
  src/controllers/notification/notifications.controller.js
  src/controllers/order/order.controller.js
  src/controllers/order/updateOrderStatus.controller.js
  src/database/migrations/20230323050734-create-order.js
  src/database/migrations/20230425130623-create-order-product.js
  src/database/models/cart.js
  src/database/models/index.js
  src/database/models/order.js
  src/database/models/orderproduct.js
  src/database/models/product.js
  src/database/models/user.js
  src/database/seeders/20230415092102-create-order.js
  src/middleware/auth/auth.middleware.js
  src/routes/order.routes.js
  tests/order/mark.shipped.test.js
  tests/order/mark.shipped.tets.js
Labels: Ready to Merge
