Repository atlp-rwanda/e-comm-team-techtitans-bn, pull requests merged in 2023-05, with the labels that each got.

#76 #184752238 A Seller Should see statistics in a given time frame
  lib/controllers/statistics/statistics.controller.js
  lib/database/models/product.js
  lib/routes/index.js
  lib/routes/statistics.routes.js
  src/controllers/statistics/statistics.controller.js
  src/database/models/product.js
  src/routes/index.js
  src/routes/statistics.routes.js
Labels: Ready to Merge

#85 #184752238 Fix - A Seller Should see statistics in a given time frame.
  lib/controllers/statistics/statistics.controller.js
  src/controllers/statistics/statistics.controller.js
Labels: Ready to Merge

#73 #184842288 feature : automated postgres backups
  backup.sh
  index.backup.js
  lib/app.js
  package-lock.json
  package.json
  src/app.js
Labels: Fixing, Ready to Merge

#83 implement coveralls code coverage
  .circleci/config.yml
  .coveralls.yml
  README.md
  src/database/seeders/20230415092102-create-order.js
Labels: Needs Rebase, Need Peer Review

#82 #184752270 fix(checkout):checkout process should include actual amount from orders.
  lib/controllers/order/order.controller.js
  lib/controllers/product/checkout.controller.js
  lib/controllers/user/pay.controller.js
  src/controllers/order/order.controller.js
  src/controllers/product/checkout.controller.js
  src/controllers/user/pay.controller.js
  tests/mocks/checkout.mock.js
  tests/mocks/payToken.mock.js
  tests/product/checkout.test.js
  tests/product/product.test.js
  tests/product/stripePayment.test.js
  tests/user/setRoles.test.js
  tests/user/signup_login.test.js
Labels: Need Peer Review

#71 #184842333 ft(newsletter- signup):Implement Newsletter Signup
  automated-backups/titans-2023-5-5-0-14.backup
  automated-backups/titans-2023-5-5-0-15.backup
  automated-backups/titans-2023-5-5-0-19.backup
  automated-backups/titans-2023-5-5-0-20.backup
  automated-backups/titans-2023-5-5-0-21.backup
  automated-backups/titans-2023-5-5-0-22.backup
  automated-backups/titans-2023-5-5-0-24.backup
  automated-backups/titans-2023-5-5-0-25.backup
  automated-backups/titans-2023-5-5-0-26.backup
  automated-backups/titans-2023-5-5-0-27.backup
  automated-backups/titans-2023-5-5-0-8.backup
  lib/app.js
  lib/controllers/product/product.controller.js
  lib/controllers/subscriber/service.schedule.controller.js
  lib/controllers/subscriber/signup.controller.js
  lib/database/config/config.js
  lib/database/migrations/20230425063607-create-subscriber.js
  lib/database/models/index.js
  lib/database/models/subscriber.js
  lib/middleware/auth/auth.middleware.js
  lib/routes/user.routes.js
  lib/utils/send.email.js
  lib/utils/subscriber.email.js
  package-lock.json
  package.json
  src/app.js
  src/controllers/notification/notifications.controller.js
  src/controllers/product/product.controller.js
  src/controllers/subscriber/service.schedule.controller.js
  src/controllers/subscriber/signup.controller.js
  src/controllers/user/findAllUsers.controller.js
  src/database/config/config.js
  src/database/migrations/20230425063607-create-subscriber.js
  src/database/models/index.js
  src/database/models/subscriber.js
  src/middleware/auth/auth.middleware.js
  src/routes/user.routes.js
  src/utils/send.email.js
  src/utils/subscriber.email.js
  views/pages/message.ejs
  views/promotion.handlebars
Labels: Ready to Merge

#93 fix(test):failing test
  automated-backups/titans-2023-5-5-15-26.backup
  automated-backups/titans-2023-5-5-15-31.backup
  automated-backups/titans-2023-5-5-15-32.backup
  automated-backups/titans-2023-5-5-15-33.backup
  automated-backups/titans-2023-5-5-15-34.backup
  automated-backups/titans-2023-5-5-15-35.backup
  automated-backups/titans-2023-5-5-15-36.backup
  automated-backups/titans-2023-5-5-15-37.backup
  automated-backups/titans-2023-5-5-15-40.backup
  tests/cart/createCart.test.js
  tests/notification/notification.test.js
  tests/product/wishlist.test.js
  tests/user/enableDisableAccount.test.js
  tests/user/updateProfile.test.js
Labels: Ready to Merge

#96 fix-setup-user-roles
  automated-backups/test-e-commerce-2023-5-29-22-14.backup
  automated-backups/test-e-commerce-2023-5-30-10-19.backup
  lib/controllers/user/2fauthentication.controller.js
  lib/controllers/user/findAllUsers.controller.js
  lib/controllers/user/role.controller.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/seeders/20230322155518-techtitans.js
  lib/database/seeders/20230429152955-create-category.js
  lib/database/seeders/20230429153310-create-product.js
  lib/database/seeders/20230429161554-create-cart.js
  lib/database/seeders/20230505120730-notification.js
  lib/database/seeders/20230505155655-demo-review.js
  lib/middleware/auth/check.password.update.js
  lib/routes/user.routes.js
  src/controllers/user/2fauthentication.controller.js
  src/controllers/user/findAllUsers.controller.js
  src/controllers/user/role.controller.js
  src/database/migrations/20230322155803-create-user.js
  src/database/seeders/20230322155518-techtitans.js
  src/database/seeders/20230429152955-create-category.js
  src/database/seeders/20230429153310-create-product.js
  src/database/seeders/20230429161554-create-cart.js
  src/database/seeders/20230505120730-notification.js
  src/database/seeders/20230505155655-demo-review.js
  src/middleware/auth/check.password.update.js
  src/routes/user.routes.js
Labels: Ready to Merge

#97 fixes view and update profile
  lib/controllers/user/forgotPassword.controller.js
  lib/controllers/user/profile.controller.js
  lib/database/migrations/20230322155803-create-user.js
  lib/database/models/user.js
  lib/routes/user.routes.js
  src/controllers/user/profile.controller.js
  src/database/migrations/20230322155803-create-user.js
  src/database/models/user.js
  src/routes/user.routes.js
Labels: Ready to Merge
